#!/bin/bash

function get_org_of_current_repo() {
    local orgs_from_global_config=$(git config --global --get-regexp ^orgs. | cut -d . -f 2)

    for org in $orgs_from_global_config; do
        local org_remotes=$(git remote -v | grep -i $org/)

        if [ ! -z "$org_remotes" ]; then
            echo $org
        fi
    done
}


org=$(get_org_of_current_repo)

if [ ! -z "$org" ]; then
    email_from_global_config=$(git config --global orgs\.$org\.email)
    email_from_local_config=$(git config user.email)

    if [ "$email_from_global_config" != "$email_from_local_config" ]; then
        echo "Organization '$org' identified!"
        echo "Setting the configured e-mail <$email_from_global_config>"
        git config user.email $email_from_global_config

        echo "Please repeat the commit command to use the new e-mail"
        exit 1
    fi
fi
